//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductLabelPrinting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchContainerItem
    {
        public int Id { get; set; }
        public int BatchContainerId { get; set; }
        public decimal NetWeight { get; set; }
        public decimal TareWeight { get; set; }
        public decimal GrossWeight { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedBy { get; set; }
    
        public virtual BatchContainerMaster BatchContainerMaster { get; set; }
    }
}
