//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductLabelPrinting.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductLabelPrintingDbEntities : DbContext
    {
        public ProductLabelPrintingDbEntities()
            : base("name=ProductLabelPrintingDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmplyoeeMaster> EmplyoeeMasters { get; set; }
        public virtual DbSet<BatchContainerItem> BatchContainerItems { get; set; }
        public virtual DbSet<BatchContainerMaster> BatchContainerMasters { get; set; }
        public virtual DbSet<BatchMaster> BatchMasters { get; set; }
        public virtual DbSet<ProductMaster> ProductMasters { get; set; }
    }
}
