//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductLabelPrinting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductMaster()
        {
            this.BatchMasters = new HashSet<BatchMaster>();
        }
    
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string UniqueCode { get; set; }
        public string CAS { get; set; }
        public string ChemicalFormula { get; set; }
        public string ManufacturerLicence { get; set; }
        public decimal MolecularWeight { get; set; }
        public string MasterLabel { get; set; }
        public string StorageConditon { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string FinishMode { get; set; }
        public Nullable<int> FinishMonth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchMaster> BatchMasters { get; set; }
        public virtual EmplyoeeMaster EmplyoeeMaster { get; set; }
    }
}
